site_name: django-readers
site_description: A lightweight function-oriented toolkit for better organisation of business logic and efficient selection and projection of data in Django projects.

theme:
  name: 'material'
  icon:
    logo: 'material/book-open-variant'
  favicon: img/favicon.ico
  palette:
    primary: pink
    accent: pink


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

repo_name: dabapps/django-readers
repo_url: https://github.com/dabapps/django-readers/
edit_uri: ""

nav:
  - Introduction: 'index.md'
  - Tutorial: 'tutorial.md'
  - Cookbook: 'cookbook.md'
  - Explanation: 'explanation.md'
  - Reference: 'reference.md'
